/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package botpubblicita;

import static botpubblicita.Analizza.locations;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import telegramapi.*;

/**
 *
 * @author iania_daniele
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTesto = new javax.swing.JTextField();
        txtCitta = new javax.swing.JTextField();
        btnInserisci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDistanza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestoActionPerformed(evt);
            }
        });

        txtCitta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCittaActionPerformed(evt);
            }
        });

        btnInserisci.setText("INSERISCI");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });

        jLabel1.setText("TESTO");

        jLabel2.setText("CITTA'");

        txtDistanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanzaActionPerformed(evt);
            }
        });

        jLabel3.setText("DISTANZA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTesto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCitta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserisci, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDistanza)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCitta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(btnInserisci)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestoActionPerformed

    private void txtCittaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCittaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCittaActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed

        String url = "https://nominatim.openstreetmap.org/search?q=";
        
        String v[] = txtCitta.getText().split(" ");
        String path = "";
        try {
            path = URLEncoder.encode(Analizza.getLocation(v, 0), "UTF-8");
            System.out.println(path);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        url += path + "&format=xml&addressdetails=1";
       // System.out.println(url);
        try {
            URL fileUrl = new URL(url);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
       // System.out.println(url);
        try {
            locations = XMLParser.parseDocument(url);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        Location location = locations.get(0);//prendo la prima città per convenzione
        System.out.println("lat: " + location.lat + " lon: " + location.lon);
        ArrayList<String> utenti = File.read();
        String utente[] = new String[3];
        double lat, lon;
        for (int i = 0; i < utenti.size(); i++) {
            utente = utenti.get(i).split(";");
            lat = Double.parseDouble(utente[1]);
            lon = Double.parseDouble(utente[2]);
            if (distanza(lat, lon, location.lat, location.lon) <= Integer.parseInt((txtDistanza.getText()))) {
                try {
                    botMethods.sendMessage(Integer.parseInt(utente[0]), txtTesto.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void txtDistanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanzaActionPerformed

    public double degreesToRadians(double degrees) {
        return degrees * Math.PI / 180;
    }

    public double distanza(double lat1, double lon1, double lat2, double lon2) {
        var earthRadiusKm = 6371;

        var dLat = degreesToRadians(lat2 - lat1);
        var dLon = degreesToRadians(lon2 - lon1);

        lat1 = degreesToRadians(lat1);
        lat2 = degreesToRadians(lat2);

        var a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
                + Math.sin(dLon / 2) * Math.sin(dLon / 2) * Math.cos(lat1) * Math.cos(lat2);
        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        return earthRadiusKm * c;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        final String baseUrl = "https://api.telegram.org/bot";
        final String token = "5024404474:AAFdg91NpLQAHZvMeM1SRpJFsyKzhFmh1Y8/";

        botMethods b = new botMethods();

        //  b.sendMessage(661819829, "bro");
        TListener listener = new TListener(b, "https://api.telegram.org/bot5024404474:AAFdg91NpLQAHZvMeM1SRpJFsyKzhFmh1Y8/getUpdates");
        listener.start();
        try {
            listener.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(BotPubblicita.class.getName()).log(Level.SEVERE, null, ex);
        }
        b.getUpdates("https://api.telegram.org/bot5024404474:AAFdg91NpLQAHZvMeM1SRpJFsyKzhFmh1Y8/getUpdates");
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserisci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCitta;
    private javax.swing.JTextField txtDistanza;
    private javax.swing.JTextField txtTesto;
    // End of variables declaration//GEN-END:variables
}
